apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acquisitions-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "acquisitions-api.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: acquisitions-service
            port:
              number: 3000