apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secret
type: Opaque
data:
  NEON_API_KEY: bmFwaV9samM4eGEyYm1jMzlmNnFyM2k3Y2t3Nng3azZqMDQxeGU1MTBiYWQweHJkc3ZkcDlpY3BzemV6cHp2ZzBvcWgy
  ARCJET_KEY: YWprZXlfMDFrY2VwYXZ4N2VrNGFocHZrYWtuZDNlajQ=